export const slides = [
  {
    key: 1,
    category: "OUTDOOR SPORTS",
    sports: ["FIELD FOOTBALL BOYS",
            "BASKETBALL BOYS",
            "BASKETBALL GIRLS",
            "BOX CRICKET BOYS",
            "BOX CRICKET GIRLS",
            "VOLLEYBALL BOYS",
            "VOLLEYBALL GIRLS",
            "KABADDI BOYS",
            "DODGEBALL GIRLS",
            "RINK FOOTBALL BOYS",
            "RINK FOOTBALL GIRLS",
            "TUG OF WAR BOYS",
            "TUG OF WAR GIRLS"],
  },
  {
    key: 2,
    category: "INDOOR SPORTS",
    sports: ["TABLE TENNIS SINGLES BOYS",
            "TABLE TENNIS DOUBLES BOYS",
            "CARROM SINGLES BOYS",
            "PICKLEBALL DOUBLES BOYS",
            "TABLE TENNIS SINGLES GIRLS",
            "TABLE TENNIS DOUBLES GIRLS",
            "CARROM SINGLES GIRLS",
            "PICKLEBALL DOUBLES GIRLS",
            "CHESS MIXED",
            "CARROM DOUBLES MIXED"],
  },
  {
    key: 3,
    category: "ATHLETICS",
    sports: ["ATHLETICS [BOYS]", "ATHLETICS [GIRLS]"],
  },
  {
    key: 4,
    category: "GAMING",
    sports: ["BGMI",
            "VALORANT",
            "CLASH ROYALE",
            "FIFA",
            "FORZA",
            "PES"],
  },
  {
    key: 5,
    category: "PERFORMING ARTS",
    sports: ["SOLO SINGING (REGIONAL)",
            "SOLO SINGING (WESTERN)",
            "DUET SINGING",
            "INSTRUMENTAL",
            "SOLO DANCING (WESTERN)",
            "SOLO DANCING (REGIONAL)",
            "DRAMA",
            "SOLO DANCE BATTLE",
            "GROUP DANCE",
            "FASHION SHOW",
            "FACULTY TALENT SHOW"],
  },
  {
    key: 6,
    category: "LITERARY ARTS",
    sports: ["GROUP DEBATE",
            "DUO DEBATE",
            "ELOCUTION",
            "POETRY / SHAYARI",
            "OPEN MIC PERFORMANCES",
            "NARRATIVE KNOCKOUT"],
  },
  {
    key: 7,
    category: "FINE ARTS",
    sports: ["SHUTTER PAINTING",
            "POT PAINTING",
            "ACT & ART",
            "TOTE BAG PAINTING"],
  },
  {
    key: 8,
    category: "COVERAGE",
    sports: ["CANDID PHOTOGRAPHY",
            "REEL MAKING",
            "SHORT FILM"],
  },
  {
    key: 9,
    category: "MEGA AND FUN",
    sports: ["OBSTACLE RACE",
            "TREASURE HUNT",
            "7 UP & 7 DOWN CHALLENGE",
            "BALLOON GUN SHOOTING",
            "RC CAR RACING",
            "GUESS THE DRINK / OBJECT"],
  },
];
